version: "1.0.3"
services:
  db:
    image: mysql:8.0.34
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      # ping if mysql server accept connections
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:5.4.1
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_db
    ports:
      - 8080:${DOCKER_ADMINER_PORT}

  api:
    depends_on:
      db:
        condition: service_healthy
    build: ./
    restart: on-failure
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - ${NODE_SERVER_PORT}:${DOCKER_NODE_SERVER_PORT}
    command: ['sh', './docker/start-api.sh']

volumes:
  db-data:


